# Generated by Django 6.0.3 on 2026-03-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('rain', 'Rain Probability'), ('temperature_high', 'High Temperature'), ('temperature_low', 'Low Temperature'), ('wind', 'Wind Speed'), ('humidity', 'Humidity')], max_length=20)),
                ('threshold', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
