# Generated by Django 6.0.3 on 2026-03-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherAlert',
        ),
    ]
