# Generated by Django 6.0.3 on 2026-03-20 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country_code')},
        ),
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('condition_description', models.CharField(max_length=200)),
                ('rain_probability', models.IntegerField(default=0)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='weather.city')),
            ],
            options={
                'db_table': 'forecast_records',
                'ordering': ['forecast_date'],
                'unique_together': {('city', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('visibility', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.IntegerField(default=0)),
                ('cloudiness', models.IntegerField(default=0)),
                ('condition', models.CharField(max_length=100)),
                ('condition_description', models.CharField(max_length=200)),
                ('rain_1h', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='weather.city')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weather_records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.DeleteModel(
            name='WeatherSnapshot',
        ),
        migrations.AddIndex(
            model_name='weatherrecord',
            index=models.Index(fields=['city', '-recorded_at'], name='weather_rec_city_id_c884c6_idx'),
        ),
    ]
